import type { ResponseSource } from "@/features/chat/types/chat.types";

export interface SourceLabel {
  label: string;
  description: string;
  /** Tailwind classes for the badge; kept beside the label so the
   *  source vocabulary lives in exactly one place. */
  className: string;
}

const SOURCE_LABELS: Record<ResponseSource, SourceLabel> = {
  llm: {
    label: "General knowledge",
    description: "Answered by the local language model.",
    className: "border-slate-200 bg-slate-50 text-slate-700",
  },
  postgresql: {
    label: "Internal workforce data",
    description: "Answered using internal workforce records.",
    className: "border-emerald-200 bg-emerald-50 text-emerald-700",
  },
  github_mcp: {
    label: "Current GitHub data",
    description: "Answered using live public GitHub data.",
    className: "border-sky-200 bg-sky-50 text-sky-700",
  },
  multi_source: {
    label: "Workforce + GitHub",
    description: "Combines internal workforce data with GitHub data.",
    className: "border-violet-200 bg-violet-50 text-violet-700",
  },
};

const UNKNOWN_SOURCE: SourceLabel = {
  label: "Assistant response",
  description: "Generated by the assistant.",
  className: "border-slate-200 bg-slate-50 text-slate-700",
};

export function getSourceLabel(source: string | undefined): SourceLabel {
  if (!source) {
    return UNKNOWN_SOURCE;
  }

  return SOURCE_LABELS[source as ResponseSource] ?? UNKNOWN_SOURCE;
}

const TOOL_LABELS: Record<string, string> = {
  search_employees: "Employee search",
  get_employee_details: "Employee details",
  get_employee_statistics: "Workforce statistics",
  analyze_workforce_skills: "Skill analysis",
  search_github_repositories: "GitHub search",
  get_github_repository_details: "Repository details",
};

/** Falls back to a title-cased version of an unmapped tool name. */
export function getToolLabel(toolName: string): string {
  const mapped = TOOL_LABELS[toolName];

  if (mapped) {
    return mapped;
  }

  const words = toolName.replace(/[_-]+/g, " ").trim();

  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function formatSimilarityScore(score: number | null | undefined): string | null {
  if (typeof score !== "number" || Number.isNaN(score)) {
    return null;
  }

  return `${Math.round(score * 100)}% match`;
}
